title: My Student Years Documentation
description: A website that hosts all the documentation for the MSY Moodle website
theme: just-the-docs

url: https://mystudentyears.github.io

aux_links:
  Template Repository: https://github.com/mystudentyears/mystudentyears.github.io
